check for /etc/os-release and bad case

diff --git a/roaster b/roaster
--- a/roaster
+++ b/roaster
@@ -2,6 +2,8 @@
 
 ########## don't change anything below this line ##########
 
+RCC=$(pwd)
+
 # Roaster base settings
 RVE="$HOME/RVE"
 RCO="$HOME/.roaster"
@@ -32,13 +34,18 @@ echo -e "Use 'roaster --help' for the available options.\n"
 command -v awk   >/dev/null 2>&1 || { echo >&2 "'awk'  (required)"; exit; }
 command -v cat   >/dev/null 2>&1 || { echo >&2 "'cat'  (required)"; exit; }
 command -v tar   >/dev/null 2>&1 || { echo >&2 "'tar'  (required)"; exit; }
+command -v pwd   >/dev/null 2>&1 || { echo >&2 "'pwd'  (required)"; exit; }
 command -v wget  >/dev/null 2>&1 || { echo >&2 "'wget' (required)"; exit; }
 command -v grep  >/dev/null 2>&1 || { echo >&2 "'grep' (required)"; exit; }
 command -v sudo  >/dev/null 2>&1 || { echo >&2 "'sudo' (required)"; exit; }
 
 # Check Linux distribution
 function check-os-info {
-	DISTRO_OS=$(cat /etc/os-release| grep ^NAME= | awk -F'"' '{$0=$2}1')
+	if [[ -f /etc/os-release ]]; then
+		DISTRO_OS=$(cat /etc/os-release| grep ^NAME= | awk -F'"' '{$0=$2}1')
+	else
+		echo "Can't find /etc/os-release."
+	fi
 }
 check-os-info
 
@@ -183,14 +190,18 @@ function R-build-virtualenv {
 		--disable-rpath $OPTRVE && make \
 		&& make install \
 		&& make clean
-	if [[ -f $RVE/bin/R ]]; then
-		mv $RVE/bin/R $RVE/bin/RVE
-		export PATH="$PATH:$RVE/bin/"
-	fi
-#	echo -e "local({\n\toptions(prompt='(RVE)> ')\n})" > $RVE/.RProfile
-	echo -e "\n\e[32mBuild done. Trying command 'RVE'...\e[0m"
-	echo -e "(Please, add '$RVE/bin/' to your PATH)\n"
-	cd $HOME && RVE
+#	if [[ -f $RVE/bin/R ]]; then
+#		mv $RVE/bin/R $RVE/bin/RVE
+#		export PATH="$PATH:$RVE/bin/"
+#	fi
+	echo -e "\n\e[32mBuild done.\e[0m"
+	echo -e "\e[32mActivating virtual environment...\e[0m"
+	cat $RRC/data/activate > $RVE/bin/activate
+	echo -e " Enable: 'source ~/RVE/bin/activate'"
+	echo -e "Disable: 'deactivate'"
+#	echo -e "\n\e[32mBuild done. Trying command 'RVE'...\e[0m"
+#	echo -e "(Please, add '$RVE/bin/' to your PATH)\n"
+#	cd $HOME && RVE
 }
 
 # Option --build-standard
